kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowritecomp
spec:
  replicas: 4
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: prowritecomp
      version: v01
  template:
    metadata:
      labels:
        app: prowritecomp
        version: v01
    spec:
      containers:
      - name: prowritecomp
        image: us.icr.io/glory/myrepo
        ports:
        - containerPort: 5000